---
title: "Supreme Court Justices"
author: "Joe Stoica"
date: "6/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(ggthemes)
library(lubridate)
```

```{r data, warning=FALSE}
URL <- "https://en.wikipedia.org/wiki/List_of_Justices_of_the_Supreme_Court_of_the_United_States"

justices <- URL %>% 
  read_html %>%  
  html_node("table.wikitable") %>% 
  html_table(fill = TRUE) %>% 
  data.frame()

# Removes weird row at bottom of the table
n <- nrow(justices)
justices <- justices[1:(n - 1), ]

# Separates columns correctly
justices <- justices %>% 
  separate(Justice.2, into = c("name","year"), sep = "\\(") %>% 
  separate(Tenure, into = c("start", "end"), sep = "\n–") %>% 
  separate(end, into = c("end", "reason"), sep = "\\(") 

# Removes wikipedia tags in columns
justices$name <- gsub('\\[g\\]$','', justices$name)
justices$start <- gsub('\\[e\\]$|\\[m\\]|\\[j\\]$','', justices$start)
justices$reason <- gsub('\\)$', '', justices$reason)

# Convert to mdy format for ggplotS to understand
justices$start <- as.Date(mdy(justices$start), format = "%m/%d/%Y")
justices$end = as.Date(mdy(justices$end), format = "%m/%d%/Y")

# Incumbent judges are still around! 
justices$end[is.na(justices$end)] <- today()
justices$reason[is.na(justices$reason)] <- "Incumbent"

# Shortening for plotting purposes
justices$reason <- ifelse(justices$reason == "Continued as chief justice", "Continued", justices$reason)
justices$reason <- ifelse(justices$reason == "Resigned, nomination having been rejected", "Resigned", justices$reason)
justices$name <- ifelse(justices$name == "Lucius Quintus\nCincinnatus Lamar II", "Lucius Q.C. Lamar II", justices$name)
```

Reordering gave me a lot of issues, here is a stack overflow post I asked about it. 
https://stackoverflow.com/questions/51109856/reorder-not-working-in-ggplot-with-my-current-data-frame
```{r}
p <- justices %>% 
  # Makes the order of justices chronological
  mutate(name = as.factor(name) %>%
           fct_reorder(start, min)) %>%
  ggplot(aes(x = name, col = reason)) +
  geom_segment(aes(xend = name,
                   yend = start,
                   y = end),
               size = 1.1,
               lineend = "round") +
  theme_set(theme_fivethirtyeight(base_size = 18)) +
  coord_flip() +  
  theme(axis.title = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 11),
        plot.caption = element_text(size = 8),
        plot.title = element_text(hjust = 0.5),
        axis.text = element_text(size = 10)) +
  labs(title = "Supreme Court Justices' Tenures",
       caption = "@Joe_Stoica") +
  guides(col = guide_legend(keywidth = 3.5,
                      keyheight = .75, 
                      title = "", 
                      label.position = "top", 
                      label.hjust = 0.5,
                      nrow = 1)) +
  scale_y_date(breaks = seq(as.Date("1790-01-01"), 
                            as.Date("2010-12-31"),
                            by = "10 years"), 
               date_labels = "%Y") +
  scale_color_manual(values = c('#e41a1c','#377eb8','#4daf4a','#984ea3','#ff7f00','#a65628')) +
  NULL

ggsave(p, filename = "justices.png", height = 20, width = 15)
```